#!/usr/bin/env bash
# Copyright 2018 Barbarians.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# Usage: start-ignite
# Starts an IGFS server.

USER=`whoami`
HOST=`hostname -s`
DOMAIN=`hostname -d`

function print_usage() {
echo "\
Usage: start-ignite
Starts an IGFS server.
"
}

CONTROL_DIR=`dirname $(readlink -f $0)`
source $CONTROL_DIR/common-functions.sh

export HADOOP_CLASSPATH=/opt/barbarian/ignite/config:/opt/barbarian/hadoop/share/hadoop/common/lib/*:/opt/barbarian/hadoop/share/hadoop/common/*:/opt/barbarian/hadoop/share/hadoop/tools/*:/opt/barbarian/hadoop/share/hadoop/tools/lib/*
export IGNITE_CUSTOM_CLASSPATH=$HADOOP_CLASSPATH

exec $IGNITE_HOME/bin/ignite.sh
