apiVersion: v1
kind: Service
metadata:
  name: ignite-cs
  labels:
    app: ignite
spec:
  ports:
  - port: 10500
    name: server
  selector:
    app: ignite
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ignite-pdb
spec:
  selector:
    matchLabels:
      app: ignite
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ignite
spec:
  selector:
    matchLabels:
      app: ignite
  serviceName: ignite-cs
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: ignite
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - ignite
              topologyKey: "kubernetes.io/hostname"
      containers:
      - image: 535272059665.dkr.ecr.eu-west-1.amazonaws.com/ignite
        name: ignite
        securityContext:
          allowPrivilegeEscalation: false
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: secret-key
          - name: AWS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: aws-bucket
                key: aws-s3-bucket
        volumeMounts:
        - mountPath: /opt/barbarian/ignite/config
          name: igfs-cfg-volume
        resources:
          requests:
            memory: "5Gi"
            cpu: "0.5"
        ports:
        - containerPort: 10500
          name: server
        command:
        - sh
        - -c
        - "/opt/barbarian/control/start-ignite \
          --conf_dir=/opt/barbarian/ignite/config \
          --log_level=INFO \
          --log_dir=/var/log/ignite \
          --zk_service=zk-cs.default.svc.cluster.local"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "/opt/barbarian/control/ignite-ready 10500"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "/opt/barbarian/control/ignite-ready 10500"
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: igfs-cfg-volume
        emptyDir: {}
